title: Core Configuration
description: An Advanced Guide for running Mac OS X / macOS on Non-Apple Hardware.
theme: just-the-docs
color_scheme: custom
favicon_ico: "/assets/favicon.ico"
nav_sort: case_sensitive

url: https://Carnations-Botanica.github.io/Core-Configuration-Docs

callouts_opacity: 0.4
callouts:
  highlight:
    color: canary
  important:
    title: Important
    color: blueish
  new:
    title: New
    color: teal
  note:
    title: Note
    color: grey-lt
  warning:
    title: Warning
    color: reddish
  headsup:
    title: Heads Up!
    color: heads-up

# set up collections

# Define Jekyll collections
collections:
  notinghardware:
    permalink: "/:collection/:path/"
    output: true
  supportcharts:
    permalink: "/:collection/:path/"
    output: true
  usbpreparations:
    permalink: "/:collection/:path/"
    output: true
  configfolders:
    permalink: "/:collection/:path/"
    output: true
  configplist:
    permalink: "/:collection/:path/"
    output: true
  osinstall:
    permalink: "/:collection/:path/"
    output: true
  troubleshooting:
    permalink: "/:collection/:path/"
    output: true
  postinstall:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    notinghardware:
      name: Know your Hardware
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    supportcharts:
      name: Hardware Support Check
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    usbpreparations:
      name: OpenCore USB Preparation
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    configfolders:
      name: Configuring Folders
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    configplist:
      name: Configuring config.plist
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    osinstall:
      name: Initial OS X / macOS Install
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    troubleshooting:
      name: General Troubleshooting
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    postinstall:
      name: Post Installation
      nav_exclude: false
      nav_fold: false
      search_exclude: false

# Set up includes
include:
# - _configfolders
# - _notinghardware
# - _supportcharts
# - _usbpreparations
# - _configplist
# - _osinstall
# - _troubleshooting
# - _postinstall
 - _sass
 - _layouts
 - _includes

# External navigation links
nav_external_links:
  - title: Support via Discord
    url: https://discord.gg/eDptbT9NcV
    hide_icon: false

# Aux links for the upper right navigation
aux_links:
  "View the Repo!":
    - "//github.com/Carnations-Botanica/Core-Configuration-Docs/tree/main"

# Makes Aux links open in a new tab. Default is false
# This is required for smooth operation of interlinked pages for navigation
aux_links_new_tab: false
